### ISSUE TITLE
Meta data changes to sac.jncc.gov.uk

### ISSUE THREAD

**Issue by jonparsonsjncc** [jncc/sac-microsite#23]
see attached document for discussion
aim is to use better wording for the meta data fields and help the presentation of content in the SERPs

[https://app.zenhub.com/files/138031480/02fbd062-7ee4-4240-9977-08b6108b9e02/download](https://app.zenhub.com/files/138031480/02fbd062-7ee4-4240-9977-08b6108b9e02/download)

**Comment by mattdebont** [comment]
Meta Tags are pushed into pages now, there are mechanisms to alter them within the sac codebase (i.e. there are generic keywords used across all pages now), descriptions and keywords may need review for the following types of page;

 - [ ] Main Home Page / Search Page
 - [ ] UK Site list pages (full uk, country, etc..)
 - [ ] Habitat / Species List pages
 - [ ] Habitat Pages
   - [ ] Map Pages
   - [ ] Distribution Map Pages
   - [ ] Comparison Pages
 - [ ] Species Pages
   - [ ] Map Pages
   - [ ] Distribution Map Pages
   - [ ] Comparison Pages
